delete from product;
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "TAG" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT_TAG" CASCADE CONSTRAINTS;
DROP TABLE "ORDER_" CASCADE CONSTRAINTS;
DROP TABLE "ORDER_PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "CART" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW_LIKE" CASCADE CONSTRAINTS;
DROP TABLE "IMG" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT_IMG" CASCADE CONSTRAINTS;
DROP TABLE "DETAIL_IMG" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW_IMG" CASCADE CONSTRAINTS;
DROP TABLE "QA" CASCADE CONSTRAINTS;
drop sequence tag_seq;
drop sequence product_seq;
drop sequence order_seq;
drop sequence qa_seq;
drop sequence review_seq;
drop sequence img_seq;
drop sequence cart_seq;

-- 다 실행 시키고 커밋해야 적용됩니다
commit;
